version: "3.3"
services:

  # Database - Mongo DB
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=trello-clone
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - TC_mongo_data:/data/db
    networks:
      - mongo-compose-network

  # Database Manager
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8099:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${ROOT_USERNAME}:${ROOT_PASSWORD}@mongo:27017
      ME_CONFIG_BASICAUTH_USERNAME: ${ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PASSWORD}
    networks:
      - mongo-compose-network
    links:
      - mongo
    restart: always

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  TC_mongo_data:
    external: false