name: ğŸ¡ CI

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: '17 12 * * 2'

jobs:
  ci:
    name: 'ğŸ¡ CI'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“š Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          clean: true
      - name: ğŸ“ Show latest commit
        run: |
          git log -1
      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: ğŸ“¦ Install dependencies
        run: yarn
      - name: ğŸ’„ Run lint
        run: yarn lint
      - name: ğŸ”§ Build app
        run: yarn build
  analyze:
    name: 'ğŸ“Š CodeQL: Code analysis'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['typescript', 'javascript']
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support

    steps:
      - name: ğŸ“š Checkout
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: ğŸŸ¢ Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      - name: ğŸ”§ Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: ğŸ“Š Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
